### PR TITLE
add Meteo&Shortwave

### PR DESCRIPTION
**Pull request by paulcarroty**

### CODE REVIEW

**Comment by Kazhnuz** [comment]
Thanks for the PR ! I'm just a bit unsure about Shortwave, as for now it is still in heavy developpement (even if it's a pretty interesting project) and that I didn't got the time to test it yet. Is it already in a usable state ?

Meteo LGTM, though

**Comment by paulcarroty** [comment]
> Is it already in a usable state ?

Yep, the author recommend to build it from GNOME Builder, check the Readme.

**Comment by BrainBlasted** [comment]
Shortwave is _not_ usable yet. I'd wait for the first release. Build instructions are for contributing, not for usage.

**Comment by Kazhnuz** [comment]
Okay, thanks for the informations !

@paulcarroty is it possible to split the commits, or do you want me to do it ? :)

Thanks again for the contribution (and sorry for not having been present)

**Comment by paulcarroty** [comment]
@Kazhnuz it's time :smile:

**Comment by BrainBlasted** [comment]
Again, I'd wait for the first release. Shortwave is still in heavy development.

**Comment by paulcarroty** [comment]
Have nothing against the heavy development, but:

* UI without lags/crashes
* stations import/export works too
* no sound issues 
* recorded couple of tracks, probably works too

**Comment by haecker-felix** [comment]
Shortwave is currently still in heavy development, so I suggest that it doesn't get added to the list *yet*. I would wait for the first beta release first at least.

@paulcarroty yes it may be usable already, but things can break anytime. Also few important features are still missing.

**Comment by BrainBlasted** [comment]
@haecker-felix is the developer of Shortwave, so consider that the official word on this.

**Comment by Kazhnuz** [comment]
Thanks for the information, @haeker-felix and @BrainBlasted ! 

So I'll put the label "awaiting stable release". If you don't mind, @paulcarroty, it would be nice to split this into two commit, to merge separatedly Meteo and Shortwave :) It would allow us to merge one, and to wait stable release for the other.

**Comment by Kazhnuz** [comment]
Shortwave have hit stable, can you/do you want to rebase, or do you prefer that I add it myself ?

**Comment by Kazhnuz** [comment]
I added it, so I'm closing this PR

**Pull request closed without merging**
