### PR TITLE
added Spot

### PR DESCRIPTION
**Pull request by mentos1386**
Added Spot. Spotify client for Gnome. https://github.com/xou816/spot

### CODE REVIEW

**Comment by Kazhnuz** [comment]
Thanks for the contribution !

Just one nit : you don't need to indicate that it's a GTK application or that it's made for the GNOME Desktop, as it's the goal of the list :) I'm trying to reduce mentions of that on the list. 

Except that, LGTM

**Comment by mentos1386** [comment]
@Kazhnuz Fixed :)

**Comment by mentos1386** [comment]
@Kazhnuz Now it should be fixed for real :)

**Comment by Kazhnuz** [comment]
LGTM, thank you !

**Pull request merged**
