### PR TITLE
Add new GNOME apps

### PR DESCRIPTION
**Pull request by sarru1291**

### CODE REVIEW

**Comment by Kazhnuz** [comment]
Thanks for the contribution ! 

There is just one thing I'm not sure : seems that even if GTG is working on a GNOME HIG release, it doesn't seems to be released yet ? Seems that it might be preferable for this one to just wait the first official release that use the new style ? Maybe I missed the release though, but I don't seems to find it.

Boxes and Podcast LGTM though

**Comment by sarru1291** [comment]
Yes, though the development is being revived, the release is yet to come.

**Comment by Kazhnuz** [comment]
Okay, thanks for the confirmation. 

Would it be possible to then maybe split the PR in two, so I can add Podcast and Boxes now, and add GTG when the stable release would be done ?

**Comment by sarru1291** [comment]
For now, I've removed the GTG. I'll PR again once it arrives.

**Comment by Kazhnuz** [comment]
Thanks for your work, LGTM :)

**Pull request merged**
